In [1]:
import pandas as pd

In [4]:
df = pd.DataFrame({"Student":["Amar","ravi","meera","kabir"],
                   "Marks":[78,87,67,90],
                   "City":["delhi","Ghaziabad","delhi","lucknow"]})

In [3]:
df

  Student  Marks       city
0    Amar     78      delhi
1    ravi     87  Ghaziabad
2   meera     67      delhi
3   kabir     90    lucknow

In [5]:
df.head(5)

  Student  Marks       City
0    Amar     78      delhi
1    ravi     87  Ghaziabad
2   meera     67      delhi
3   kabir     90    lucknow

In [6]:
df.shape

(4, 3)

In [7]:
df.dtypes

Student      str
Marks      int64
City         str
dtype: object