In [1]:
import pandas as pd

In [27]:
df = pd.DataFrame({"Student":["Amar","ravi","meera","kabir"],
                   "Marks":[78,87,67,90],
                   "City":["delhi","Ghaziabad","delhi","lucknow"]})

In [3]:
df

  Student  Marks       city
0    Amar     78      delhi
1    ravi     87  Ghaziabad
2   meera     67      delhi
3   kabir     90    lucknow

In [5]:
df.head(5)

  Student  Marks       City
0    Amar     78      delhi
1    ravi     87  Ghaziabad
2   meera     67      delhi
3   kabir     90    lucknow

In [11]:
df.shape

(4, 3)

In [7]:
df.dtypes

Student      str
Marks      int64
City         str
dtype: object

In [9]:
df.describe()

          Marks
count   4.00000
mean   80.50000
std    10.34408
min    67.00000
25%    75.25000
50%    82.50000
75%    87.75000
max    90.00000

In [14]:
df.isnull().sum()

Student    0
Marks      1
City       0
dtype: int64

In [20]:
df[["Marks","City"]]

   Marks       City
0   78.0      delhi
1    NaN  Ghaziabad
2   67.0      delhi
3   90.0    lucknow

In [21]:
df[df["Marks"]>70]

  Student  Marks     City
0    Amar   78.0    delhi
3   kabir   90.0  lucknow

In [ ]:
avg_marksbycity = df.groupby("City")["Marks"].mean()

In [23]:
avg_marksbycity

City
Ghaziabad     NaN
delhi        72.5
lucknow      90.0
Name: Marks, dtype: float64

In [29]:
avg_marksbycity = df.groupby("City")["Marks"].agg(["mean","max","count"])

In [30]:
avg_marksbycity

           mean  max  count
City
Ghaziabad  87.0   87      1
delhi      72.5   78      2
lucknow    90.0   90      1

In [31]:
address = pd.DataFrame({
    "City":["delhi","Ghaziabad","lucknow"],
    "State":["Delhi","UP","UP"]
})

In [ ]:
merged = pd.merge(df,address)

In [33]:
merged

  Student  Marks       City  State
0    Amar     78      delhi  Delhi
1    ravi     87  Ghaziabad     UP
2   meera     67      delhi  Delhi
3   kabir     90    lucknow     UP

In [34]:
merged = pd.merge(address,on = "City" , how = "left")

TypeError: merge() missing 1 required positional argument: 'right'